### ISSUE TITLE
${REF_PATH}

### ISSUE THREAD

**Issue by cxl973** [Bocabbage/G4Catcher#1]
可以请问一下数据预处理那块，${REF_PATH}是什么文件吗

**Comment by Bocabbage** [comment]
你好，${REF_PATH}是您本地的参考基因组的FASTA文件（例如hg19.fa）。

**Comment by abc-123-ship-cell** [comment]
您好，我按照示例，得到了K562细胞系和G4-seq的重叠区域的文件——plus.g4seqFirst.F0.1.ex1000.origin.bed，我也下载了hg19.fa文件，在执行命令(g4beacon seqFeatureConstruct -i plus.g4seqFirst.F0.1.bed -oseq plus.g4seqFirst.F0.1.ex1000.seq.csv -obi plus.g4seqFirst.F0.1.ex1000.origin.bed -fi ./hg19/hg19.fa)的时候出现了报错，能帮忙看一下嘛

```
Error occurs in cmd: bedtools getfasta -fi ./hg19/hg19.fa -bed 3112tmp.plus.g4seqFirst.F0.1.bed.extendG4Rigion1.bed > 3112tmp.plus.g4seqFirst.F0.1.bed.extendG4Rigion2.fa
STDERR OUTPUT:
index file ./hg19/hg19.fa.fai not found, generating...
```

**Comment by Bocabbage** [comment]
您好，在hg19.fa所在的文件夹下还应当包含一个hg19.fa.fai文件（与hg19.fa一样也可以获取）。

**Comment by abc-123-ship-cell** [comment]
您好，可以请问一下您使用的hg19的版本吗，我在生成csv文件时遇到了Feature (chr17:81193933-81196188) beyond the length of chr17 size (81195210 bp).  Skipping的问题，看起来像是染色体的长度不匹配
