### ISSUE TITLE
hg19问题

### ISSUE THREAD

**Issue by cxl973** [Bocabbage/G4Catcher#3]
您好，可以请问一下您使用的hg19的版本吗，我在生成csv文件时遇到了Feature (chr17:81193933-81196188) beyond the length of chr17 size (81195210 bp). Skipping的问题，看起来像是染色体的长度不匹配

**Comment by Bocabbage** [comment]
您好，我们默认使用的hg19版本是GCA_000001405.1。出现该问题的时候您可以检查一下所使用的hg19对应的chrom.sizes文件，看看输入的bed文件是否存在染色质坐标越界的问题。

**Comment by abc-123-ship-cell** [comment]
生成atac feature csv的时候，出现了一些报错提示，Skipping chr9:141009507-141009612, due to being absent in the computeMatrix output. 请问是否意味着这些数据应该被剔除
